#!/bin/bash

set -e

# Install Python dependencies
pip install --upgrade pip poetry
echo "--- poetry lock ---"
poetry lock

echo "--- poetry export ---"
poetry export -f requirements.txt > /tmp/requirements.txt

echo "--- cat /tmp/requirements.txt ---"
cat /tmp/requirements.txt

echo "--- pip install ---"
pip install -r /tmp/requirements.txt

# Display installed versions
python -V
poetry -V
jupyter --version
pip list

# Install NLTK corpora and tokenizers
# python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"
