#!/bin/bash

set -e

# Install Python dependencies
pip install --upgrade pip poetry
poetry export -f requirements.txt > /tmp/requirements.txt
pip install -r /tmp/requirements.txt

# Display installed versions
python -V
poetry -V
jupyter --version
pip list

# Install NLTK corpora and tokenizers
# python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"
